# Name:	Weikeng Yang
# Email: weikengyang@gmail.com
# ID:    405346443

default:
	gcc -o lab0 -g -Wall -Wextra lab0.c


check:
	./smokeTest.sh

clean:
	rm -f lab0 lab0-405346443.tar.gz

dist:
	tar -cvzf lab0-405346443.tar.gz lab0.c README smokeTest.sh Makefile backtrace.png breakpoint.png
