# NAME: Weikeng Yang
# EMAIL: weikengyang@gmail.com
# ID: 405346443

default: build

build:
	tar -czf lab4a-405346443.tar.gz build_run.png Makefile README connected.png copy.png git.png my_beaglebone.jpg


check:
	./P4A_check.sh 405346443

clean:
	-@rm -f lab4a-405346443.tar.gz


dist: clean build check
