#NAME: Zhirong Wang, Vincent Wang
#EMAIL: zwang40@mail.ccsf.edu
#ID: 105179351

.SILENT:

default:
	gcc -g -Wall -Wextra -std=gnu99 lab3a.c -o lab3a

dist:
	tar -cvzf lab3a-105179351.tar.gz lab3a.c ext2_fs.h Makefile README

clean:
	rm -f lab3a *.tar.gz *_.csv
